modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL="https://github.com/Ocelot5836/Flinting/issues"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = "Forces the player to make flint tools before wood"

[modproperties.${mod_id}]
catalogueItemIcon="flinting:flint_axe"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"